"""Feature 055 (US5 T043, render half) — standalone export document wrapper.

``render_export_document`` wraps rendered component HTML in a complete,
SELF-CONTAINED page (inline stylesheet only — no scripts, no external asset
URLs) for ``GET /api/export/canvas/{chat_id}.html``. Charts that were not
pre-degraded by ROTE still read as their accessible text (the stylesheet
surfaces the aria-label + sr-only summary); interactive chrome is suppressed.
"""
from __future__ import annotations

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from webrender.renderer import (  # noqa: E402
    render_export_document,
    render_workspace,
)


def _doc(components_html="<p>body</p>", title="My canvas",
         note="Includes tool-sourced and AI-generated content",
         generated_at="2026-07-13"):
    return render_export_document(components_html, title, note, generated_at)


# ───────────────────────── document shape ─────────────────────────────────────

def test_complete_standalone_document():
    out = _doc()
    assert out.startswith("<!DOCTYPE html>")
    assert out.endswith("</html>")
    assert "<title>My canvas</title>" in out
    assert "<style>" in out
    assert "<h1>My canvas</h1>" in out
    assert "<p>body</p>" in out  # components html embedded verbatim
    assert "Generated 2026-07-13 by AstralDeep" in out
    assert "Includes tool-sourced and AI-generated content" in out


def test_title_and_note_are_escaped():
    out = _doc(title='<script>alert(1)</script>', note='<img src=x onerror=y>')
    assert "<script" not in out
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in out
    assert "<img" not in out


def test_no_external_references_from_the_wrapper():
    out = _doc(components_html="")
    for needle in ("<script", "http://", "https://", "src=", "@import", "url("):
        assert needle not in out, needle


def test_empty_note_and_date_are_omitted_gracefully():
    out = render_export_document("<p>x</p>", "T", "", None)
    assert '<p class="export-meta">' not in out  # the CSS rule alone remains
    assert "Generated by AstralDeep" in out
    assert "Generated  by" not in out  # no dangling double space


# ───────────────────────── degradation rules ─────────────────────────────────

def test_stylesheet_degrades_charts_and_hides_live_chrome():
    css = _doc()
    # chart placeholders read as their accessible name + data summary
    assert "attr(aria-label)" in css
    assert ".astral-sr-only{display:block" in css
    # dead interactive chrome is suppressed in the static document
    assert ".astral-component-chrome" in css
    assert ".astral-pagination" in css


def test_wraps_real_workspace_render_without_scripts():
    comps = [
        {"type": "table", "component_id": "wc_a", "title": "Data",
         "headers": ["h"], "rows": [["v"]], "provenance": "grounded"},
        {"type": "bar_chart", "component_id": "wc_b", "title": "Chart",
         "labels": ["x"], "datasets": [{"label": "s", "data": [1]}]},
    ]
    inner = render_workspace(comps)  # static rendition: no profile, no chrome
    out = render_export_document(inner, "Canvas", "note", "2026-07-13")
    assert 'data-component-id="wc_a"' in out
    assert ">v<" in out  # table cell survived
    assert "astral-provenance--grounded" in out  # provenance badge carried
    assert "<script" not in out
