"""Tests for render_export_document in backend/webrender/renderer.py: the standalone
export page is self-contained, escapes its title/note, and degrades charts to
accessible text with interactive chrome hidden.
"""

from __future__ import annotations

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from webrender.renderer import (  # noqa: E402
    render_export_document,
    render_workspace,
)


def _doc(components_html="<p>body</p>", title="My canvas",
         note="Includes tool-sourced and AI-generated content",
         generated_at="2026-07-13"):
    return render_export_document(components_html, title, note, generated_at)


def test_complete_standalone_document():
    out = _doc()
    assert out.startswith("<!DOCTYPE html>")
    assert out.endswith("</html>")
    assert "<title>My canvas</title>" in out
    assert "<style>" in out
    assert "<h1>My canvas</h1>" in out
    assert "<p>body</p>" in out
    assert "Generated 2026-07-13 by AstralDeep" in out
    assert "Includes tool-sourced and AI-generated content" in out


def test_title_and_note_are_escaped():
    out = _doc(title='<script>alert(1)</script>', note='<img src=x onerror=y>')
    assert "<script" not in out
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in out
    assert "<img" not in out


def test_no_external_references_from_the_wrapper():
    out = _doc(components_html="")
    for needle in ("<script", "http://", "https://", "src=", "@import", "url("):
        assert needle not in out, needle


def test_empty_note_and_date_are_omitted_gracefully():
    out = render_export_document("<p>x</p>", "T", "", None)
    assert '<p class="export-meta">' not in out
    assert "Generated by AstralDeep" in out
    assert "Generated  by" not in out


def test_stylesheet_degrades_charts_and_hides_live_chrome():
    css = _doc()
    assert "attr(aria-label)" in css
    assert ".astral-sr-only{display:block" in css
    assert ".astral-component-chrome" in css
    assert ".astral-pagination" in css


def test_wraps_real_workspace_render_without_scripts():
    comps = [
        {"type": "table", "component_id": "wc_a", "title": "Data",
         "headers": ["h"], "rows": [["v"]], "provenance": "grounded"},
        {"type": "bar_chart", "component_id": "wc_b", "title": "Chart",
         "labels": ["x"], "datasets": [{"label": "s", "data": [1]}]},
    ]
    inner = render_workspace(comps)
    out = render_export_document(inner, "Canvas", "note", "2026-07-13")
    assert 'data-component-id="wc_a"' in out
    assert ">v<" in out
    assert 'class="astral-provenance astral-provenance--grounded' not in out
    assert "tool data" not in out
    assert "<script" not in out
