#!/usr/bin/env python3
"""Generate the private export document from exact shared public renderer assets.

Only base64 presentation data is substituted by native hosts. No model executable code, URL fetch or dependency.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "backend/webrender/static"
OUTPUT = ROOT / "contracts/assets/exports"


def _sha(value: str) -> str:
    return base64.b64encode(hashlib.sha256(value.encode()).digest()).decode()


def build() -> tuple[str, dict]:
    """Return reproducible HTML and public-source manifest without writing."""
    inputs = {}

    def read(path: Path) -> bytes:
        # Feature 089: a CRLF working tree (a Windows checkout, or a vendored
        # bundle that ships CRLF) must not change what this generator produces.
        # Normalised BEFORE the digest, not after: recording the checkout's own
        # bytes made the manifest disagree with itself between a Windows
        # checkout and the Linux image that serves the result, which is the one
        # thing a reproducibility manifest must never do. .gitattributes stores
        # this tree with LF, so LF is the canonical form of every text source.
        raw = path.read_bytes().replace(b"\r\n", b"\n")
        # POSIX-separated so the manifest is byte-identical regardless of the
        # host OS the generator runs on (Windows str() would emit backslashes).
        inputs[path.relative_to(ROOT).as_posix()] = hashlib.sha256(raw).hexdigest()
        return raw

    css = read(STATIC / "astral.css").decode()
    fonts = {}
    for name in ("open-sans-latin.woff2",):
        fonts[name] = base64.b64encode(read(STATIC / "fonts" / name)).decode()
        css = css.replace("/static/fonts/" + name, "data:font/woff2;base64," + fonts[name])
    icon = base64.b64encode(read(STATIC / "img/astra-fav.png")).decode()
    css = css.replace("/static/img/astra-fav.png", "data:image/png;base64," + icon)
    if any(not value.strip(" '\"").startswith("data:") for value in re.findall(r"url\((.*?)\)", css)):
        raise ValueError("Unbundled stylesheet URL")
    shell = read(ROOT / "backend/webrender/templates/shell.html").decode()
    start = shell.index("    tailwind.config = {")
    config = shell[start:shell.index("  </script>", start)]
    scripts = [read(STATIC / "vendor/tailwind.js").decode(), config,
               read(STATIC / "canvas-export.js").decode(),
               "window.AstralExportFonts = Object.freeze(" + json.dumps(fonts) + ");",
               read(STATIC / "canvas-export-host.js").decode()]
    if "</style" in css.lower() or any("</script" in value.lower() for value in scripts):
        raise ValueError("Asset contains an embedding boundary")
    csp = ("default-src 'none'; connect-src 'none'; frame-src 'none'; object-src 'none'; "
           "base-uri 'none'; form-action 'none'; worker-src 'none'; img-src data:; "
           "font-src data:; style-src 'unsafe-inline'; script-src " +
           " ".join("'sha256-" + _sha(value) + "'" for value in scripts))
    markup = ("<!doctype html>\n<!-- Generated by scripts/build_native_export.py. -->\n"
              '<html lang="en" data-export-state="loading"><head><meta charset="utf-8">'
              '<meta name="viewport" content="width=device-width,initial-scale=1">'
              f'<meta http-equiv="Content-Security-Policy" content="{csp}">'
              '<meta id="export-payload" content="__ASTRAL_EXPORT_PRESENTATION_BASE64__">'
              f'<style>{css}</style><style>html,body{{height:auto;min-height:100%;overflow:auto}}'
              '#astral-canvas{height:auto;max-height:none;overflow:visible;max-width:100%;margin:0 auto}'
              '#export-status{font:14px Inter,system-ui;padding:12px;color:rgb(var(--astral-muted))}</style>'
              '</head><body class="bg-astral-bg text-astral-text" data-astral-view="work">'
              '<main id="astral-canvas" class="astral-canvas-panel p-4"></main>'
              '<p id="export-status" role="status">Preparing offline export…</p>' +
              "".join("<script>" + value + "</script>" for value in scripts) + '</body></html>\n')
    manifest = {"version": "astral.canvas-export/v1", "sources": inputs,
                "template_sha256": hashlib.sha256(markup.encode()).hexdigest()}
    return markup, manifest


def main() -> int:
    """Write generated public artifacts, or refuse drift with --check."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    markup, manifest = build()
    contents = {"export.html": markup, "manifest.json": json.dumps(manifest, indent=2) + "\n"}
    if args.check:
        return 0 if all((OUTPUT / name).is_file()
                        and (OUTPUT / name).read_text(encoding="utf-8") == value
                        for name, value in contents.items()) else 1
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, value in contents.items():
        # newline="" so the artifact is LF on every host, matching the digest
        # the manifest records and the bytes .gitattributes stores.
        (OUTPUT / name).write_text(value, encoding="utf-8", newline="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
