"""Fail-closed integrity checks for the bundled Windows speech helper.

The expected digest is generated by ``AstralDeep.spec`` from the exact helper
bytes at freeze time and stored as a Python module inside the PyInstaller PYZ.
Source checkouts intentionally do not contain that generated module, so local
developer runs cannot accidentally treat an unsigned helper as release-ready.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
import ctypes
from ctypes import wintypes
import hashlib
import hmac
import importlib
from pathlib import Path
import re
import sys


_EXPECTED_DIGEST_MODULE = "_astral_helper_integrity_expected"
_EXPECTED_DIGEST_PATTERN = re.compile(r"[0-9a-f]{64}")
_EXPECTED_DIGEST_UNSET = object()


@dataclass(frozen=True, slots=True)
class HelperIntegrityResult:
    """Stable availability decision returned to the Windows client root."""

    available: bool
    reason: str


def _load_expected_digest() -> str | None:
    """Load the freeze-time digest without accepting an adjacent data file."""

    try:
        module = importlib.import_module(_EXPECTED_DIGEST_MODULE)
    except (ImportError, AttributeError, OSError):
        return None
    value = getattr(module, "EXPECTED_HELPER_SHA256", None)
    return value if isinstance(value, str) else None


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


class _Guid(ctypes.Structure):
    _fields_ = (
        ("Data1", ctypes.c_uint32),
        ("Data2", ctypes.c_uint16),
        ("Data3", ctypes.c_uint16),
        ("Data4", ctypes.c_ubyte * 8),
    )


class _WinTrustFileInfo(ctypes.Structure):
    _fields_ = (
        ("cbStruct", wintypes.DWORD),
        ("pcwszFilePath", wintypes.LPCWSTR),
        ("hFile", wintypes.HANDLE),
        ("pgKnownSubject", ctypes.POINTER(_Guid)),
    )


class _WinTrustData(ctypes.Structure):
    _fields_ = (
        ("cbStruct", wintypes.DWORD),
        ("pPolicyCallbackData", wintypes.LPVOID),
        ("pSIPClientData", wintypes.LPVOID),
        ("dwUIChoice", wintypes.DWORD),
        ("fdwRevocationChecks", wintypes.DWORD),
        ("dwUnionChoice", wintypes.DWORD),
        ("pFile", ctypes.POINTER(_WinTrustFileInfo)),
        ("dwStateAction", wintypes.DWORD),
        ("hWVTStateData", wintypes.HANDLE),
        ("pwszURLReference", wintypes.LPCWSTR),
        ("dwProvFlags", wintypes.DWORD),
        ("dwUIContext", wintypes.DWORD),
    )


_WINTRUST_ACTION_GENERIC_VERIFY_V2 = _Guid(
    0x00AAC56B,
    0xCD44,
    0x11D0,
    (ctypes.c_ubyte * 8)(0x8C, 0xC2, 0x00, 0xC0, 0x4F, 0xC2, 0x95, 0xEE),
)
_WTD_UI_NONE = 2
_WTD_REVOKE_WHOLECHAIN = 1
_WTD_CHOICE_FILE = 1
_WTD_STATEACTION_VERIFY = 1
_WTD_STATEACTION_CLOSE = 2
_WTD_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT = 0x80
_WTD_DISABLE_MD2_MD4 = 0x2000


def _load_wintrust():
    return ctypes.WinDLL("wintrust", use_last_error=True)


def _verify_authenticode(
    path: Path,
    *,
    library_loader: Callable[[], object] | None = None,
) -> bool:
    """Return whether Windows trusts the file's embedded Authenticode signature."""

    loader = library_loader or _load_wintrust
    library = loader()
    win_verify_trust = library.WinVerifyTrust
    win_verify_trust.argtypes = (
        wintypes.HWND,
        ctypes.POINTER(_Guid),
        ctypes.POINTER(_WinTrustData),
    )
    win_verify_trust.restype = wintypes.LONG

    file_info = _WinTrustFileInfo(
        cbStruct=ctypes.sizeof(_WinTrustFileInfo),
        pcwszFilePath=str(path),
        hFile=None,
        pgKnownSubject=None,
    )
    trust_data = _WinTrustData(
        cbStruct=ctypes.sizeof(_WinTrustData),
        pPolicyCallbackData=None,
        pSIPClientData=None,
        dwUIChoice=_WTD_UI_NONE,
        fdwRevocationChecks=_WTD_REVOKE_WHOLECHAIN,
        dwUnionChoice=_WTD_CHOICE_FILE,
        pFile=ctypes.pointer(file_info),
        dwStateAction=_WTD_STATEACTION_VERIFY,
        hWVTStateData=None,
        pwszURLReference=None,
        dwProvFlags=(
            _WTD_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT | _WTD_DISABLE_MD2_MD4
        ),
        dwUIContext=0,
    )

    status = None
    try:
        status = win_verify_trust(
            None,
            ctypes.byref(_WINTRUST_ACTION_GENERIC_VERIFY_V2),
            ctypes.byref(trust_data),
        )
    finally:
        trust_data.dwStateAction = _WTD_STATEACTION_CLOSE
        win_verify_trust(
            None,
            ctypes.byref(_WINTRUST_ACTION_GENERIC_VERIFY_V2),
            ctypes.byref(trust_data),
        )
    return status == 0


def verify_helper_integrity(
    helper_path: str | Path,
    *,
    expected_sha256: str | None | object = _EXPECTED_DIGEST_UNSET,
    expected_digest_loader: Callable[[], str | None] | None = None,
    digest_reader: Callable[[Path], str] | None = None,
    authenticode_verifier: Callable[[Path], bool] | None = None,
    platform: str | None = None,
) -> HelperIntegrityResult:
    """Return a fail-closed helper availability decision.

    The injectable digest and Authenticode seams keep all failure paths
    deterministic in unit tests. The helper is hashed again after signature
    validation so replacement during the trust check cannot be accepted.
    """

    path = Path(helper_path)
    try:
        if not path.is_file():
            return HelperIntegrityResult(False, "helper_missing")
    except OSError:
        return HelperIntegrityResult(False, "helper_missing")

    platform_name = sys.platform if platform is None else platform
    if platform_name != "win32":
        return HelperIntegrityResult(False, "unsupported_platform")

    if expected_sha256 is _EXPECTED_DIGEST_UNSET:
        loader = expected_digest_loader or _load_expected_digest
        try:
            expected_sha256 = loader()
        except Exception:
            return HelperIntegrityResult(False, "expected_digest_unavailable")
    if (
        not isinstance(expected_sha256, str)
        or _EXPECTED_DIGEST_PATTERN.fullmatch(expected_sha256) is None
    ):
        return HelperIntegrityResult(False, "expected_digest_unavailable")

    read_digest = digest_reader or _sha256_file
    try:
        observed_digest = read_digest(path)
    except Exception:
        return HelperIntegrityResult(False, "digest_read_failed")
    if not isinstance(observed_digest, str) or not hmac.compare_digest(
        observed_digest.lower(), expected_sha256
    ):
        return HelperIntegrityResult(False, "digest_mismatch")

    verify_signature = authenticode_verifier or _verify_authenticode
    try:
        if not verify_signature(path):
            return HelperIntegrityResult(False, "signature_invalid")
    except Exception:
        return HelperIntegrityResult(False, "signature_invalid")

    try:
        final_digest = read_digest(path)
    except Exception:
        return HelperIntegrityResult(False, "digest_read_failed")
    if not isinstance(final_digest, str) or not hmac.compare_digest(
        final_digest.lower(), expected_sha256
    ):
        return HelperIntegrityResult(False, "helper_changed_during_verification")
    return HelperIntegrityResult(True, "ready")
